version: 2

models:
  - name: stg_addresses
    description: "Staging model of addresses."
    columns:
      - name: address_uuid
        description: "Address unique identifier."

      - name: address
        description: "Composition of street number and street."

      - name: zipcode
        description: "Address's zip code."

      - name: state
        description: "Address's state."

      - name: country
        description: "Address's country."

  - name: stg_events
    description: "Every event tracked by an user on the website."
    columns:
      - name: event_uuid
        description: "Event unique identifier."

      - name: session_uuid
        description: "Session unique identifier when the event was tracked (foreign key)."

      - name: user_uuid
        description: "User unique identifier (foreign key)."

      - name: event_type
        description: "Type of event."

      - name: page_url
        description: "URL of the page where the event was tracked."

      - name: created_at_utc
        description: "Timestamp (UTC)"

  - name: stg_order_items
    description: "Each of an item on an order."
    columns:
      - name: order_uuid
        description: "Order unique identifier (foreign key)."

      - name: product_uuid
        description: "Product unique identifier (foreign key)."

      - name: quantity
        description: "Quantity of a product in an order."

  - name: stg_orders
    description: "Orders on the website."
    columns:
      - name: order_uuid
        description: "Order unique identifier."

      - name: promo_uuid
        description: "Promo unique identifier (foreign key)."

      - name: user_uuid
        description: "User unique identifier (foreign key)."

      - name: addres_uuid
        description: "Address unique identifier (foreign key)."

      - name: created_at_utc
        description: "Date of order creation."

      - name: order_cost
        description: "Cost of the order."

      - name: shipping_cost
        description: "Shipping costs."

      - name: order_total
        description: "Order total."

      - name: tracking_uuid
        description: "Tracking unique identifier."

      - name: shipping_service
        description: "Name of the shipping service."

      - name: estimated_delivery_at_utc
        description: "Estimation of the order delivery."

      - name: delivery_at_utc
        description: "Actual date of delivery."

      - name: status
        description: "Status of the order."

  - name: stg_products
    description: "Description of the available products on the website."
    columns:
      - name: product_uuid
        description: "Product unique identifier."

      - name: name
        description: "Name of the product."

      - name: price
        description: "Price of the product."

      - name: quantity
        description: "Amount of product currently available on the website."

  - name: stg_promos
    description: "Promotions."
    columns:
      - name: promo_uuid
        description: "Promotions unique identifier."

      - name: discount
        description: "Percentage of discount on the promotion (%)."

      - name: status
        description: "Status of the promotion."

  - name: stg_users
    description: "Users information."
    columns:
      - name: user_uuid
        description: "User unique identifier."

      - name: first_name
        description: "User's first name."

      - name: last_name
        description: "User's first name."

      - name: email
        description: "User's email."

      - name: phone_number
        description: "User's phone number."

      - name: created_at_utc
        description: "Date of user's sign up on the website."

      - name: updated_at_utc
        description: "Last time the information was updated."

      - name: address_uuid
        description: "Address unique identifier (foreign key)."